configuration:
  database:
    username: postgres
    host: postgres.flyte.svc.cluster.local
    dbname: flyteadmin 
    password: postgres
  storage:
    type: minio
    metadataContainer: my-s3-bucket #This is the default bucket created with Minio. Controlled by the MINIO_DEFAULT_BUCKETS env var in the local-flyte-resources.yaml manifest
    userDataContainer: my-s3-bucket
    provider: s3
    providerConfig:
      s3:
        region: "us-east-1" #Irrelevant for local but still needed
        authType: "accesskey"
        endpoint: "http://minio.flyte.svc.cluster.local:9000"
        accessKey: "minio"
        secretKey: "miniostorage" #If you need to change this parameters, refer to the local-flyte-resources.yaml manifest and adjust the MINIO_ROOT_PASSWORD env var
        disableSSL: "true"
        secure: "false"

  # inlineSecretRef: flyte-binary-inline-config-secret  
  inline:
    plugins:
      k8s:
        inject-finalizer: true
        default-env-vars:
          - FLYTE_AWS_ENDPOINT: "http://minio.flyte.svc.cluster.local:9000"
          - FLYTE_AWS_ACCESS_KEY_ID: "minio"
          - FLYTE_AWS_SECRET_ACCESS_KEY: "miniostorage" #Use the same value as the MINIO_ROOT_PASSWORD
    task_resources:
      defaults: 
        cpu: 100m
        memory: 500Mi #change default requested resources and limits to fit your needs
      limits:
        memory: 2Gi
    storage:
      cache:
        max_size_mbs: 100
        target_gc_percent: 100
        
  waitForDB:
    # image Configure image to use for wait-for-db init container
    image:
      # repository Init container image repository
      repository: postgres
      # tag Init container image tag
      tag: 15-alpine
      # pullPolicy Init container image pull policy
      pullPolicy: IfNotPresent
    # command Override default init container command
    command: []
    # args Override default init container args
    args: []
  # genAdminAuthSecret Configure init container to generate secrets for internal use
  genAdminAuthSecret:
    # command Override default init container command
    command: []
    # args Override default init container args
    args: []
  # labels Add labels to Flyte deployment
  labels: {}
  # annotations Add annotations to Flyte deployment
  annotations: {}
  # labels Add labels to Flyte pod
  podLabels: {}
  # annotations Add annotations to Flyte pod
  podAnnotations: {}
  # extraVolumeMounts Specify additional volumeMounts for Flyte container
  extraVolumeMounts: []
  # extraVolume Specify additional volumes for Flyte pod
  extraVolumes: []
  # sidecars Specify additional containers for Flyte pod
  sidecars: []
  # initContainers Specify additional init containers for Flyte pod
  initContainers: []
  # extraPodSpec Specify additional configuration for Flyte pod
  # This can be used for adding affinity, tolerations, hostNetwork, etc.
  extraPodSpec: {}
serviceAccount:
  create: true
